### ISSUE TITLE
[BUG] Custom Vending Limit

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#15]
**Describe the bug** 
The custom vending limit patch is not working on clients 2021-01-07aRagexeRE
on NEMO this patch works normally there.

**Screenshots**
![image](https://user-images.githubusercontent.com/53480357/115239324-f783b380-a0f4-11eb-86f9-a19482611f42.png)

**Comment by Neo-Mind** [comment]
This was already fixed. If you are still facing some issue please reopen

**Comment by RagnaWay** [comment]
Not yet fixed!!!
![image](https://user-images.githubusercontent.com/53480357/118059594-4d9bed80-b367-11eb-86b1-a582655565bc.png)

**Comment by Neo-Mind** [comment]
Are you using the latest version?
Tool version is 1.2.3 and Updated on 10th April 2021

**Comment by RagnaWay** [comment]
> Are you using the latest version?
> Tool version is 1.2.3 and Updated on 10th April 2021

Lasted 1.2.3! I downloaded it yesterday from git and tested it and had the same error.

**Comment by Neo-Mind** [comment]
Ah yes i see it now. Fixed in local. Will push it soon.

**Comment by Neo-Mind** [comment]
Fixes have been pushed. Please check and let me know.

**Comment by RagnaWay** [comment]
There was no error to apply the patch, but it is not allowing to sell above 1B, when I insert 2B it goes back to 1B.
even setting to sell 2B
vending_max_value: 2000000000

**Comment by Neo-Mind** [comment]
saw the issue. -__- more hardcoded checks added in new client.
I think i got them all. will push the fixes later.

**Comment by Neo-Mind** [comment]
Fixed in latest commit. Please check @RagnaWay

**Comment by RagnaWay** [comment]
> Fixed in latest commit. Please check @RagnaWay

still not working, I try for 2B but go back to 1B
![image](https://user-images.githubusercontent.com/53480357/120558202-83b41680-c3d5-11eb-920d-c8d1cef8dfde.png)

**Comment by Neo-Mind** [comment]
Found the issue, missed one position due to EAX opcode ugh. Will commit it within next few days.

**Comment by Neo-Mind** [comment]
@RagnaWay I have pushed the changes. Please check.

**Comment by RagnaWay** [comment]
Working perfectly now! Thanks.
![image](https://user-images.githubusercontent.com/53480357/121435282-fdf41600-c954-11eb-94f2-86d21e053bd1.png)

**Comment by Neo-Mind** [comment]
Ok great. Closing this then.
