### ISSUE TITLE
[BUG] Hide packet froom PEEK & BPE

### ISSUE THREAD

**Issue by RagnaWay** [Neo-Mind/WARP#68]
**Describe the bug**
This patch is causing an error on the client crashing. Tested on client 2021-01-07aRagexeRE

**Screenshots**
![image](https://user-images.githubusercontent.com/53480357/130950108-d78b254f-0d84-4c58-a2d3-fc77c54a5a99.png)

**Comment by Everade** [comment]
Confirmed

**Comment by Neo-Mind** [comment]
Fixed in local. To be pushed soon.

**Comment by RagnaWay** [comment]
> Fixed in local. To be pushed soon.
https://github.com/Neo-Mind/WARP/commit/b4a32bfc4e65ef5b8df0a2985e41b539674c5aef
Still continues to crash
![image](https://user-images.githubusercontent.com/53480357/131030848-c7cb5876-7555-4fd4-8c2d-4bb91384e914.png)

**Comment by Neo-Mind** [comment]
Strange it's not crashing for me now. @Everade  what about at your end?

**Comment by RagnaWay** [comment]
> Strange it's not crashing for me now. @Everade what about at your end?

Sorry, it's working. tested now only with recommended patches. But I'm trying to figure out which diff is now crashing.
Edit: Found the error: https://github.com/Neo-Mind/WARP/issues/72

**Comment by Neo-Mind** [comment]
Ok shall i close this then.

**Comment by RagnaWay** [comment]
Working!
